ramen %>% group_by(country) %>% filter(stars == max(stars))
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars))
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars)) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE)) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE)) %>% arrange(mean_star) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE), count = n()) %>% arrange(mean_star) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE), count = n()) %>% arrange(mean_star) %>% filter(count > 50) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% arrange(mean_star) %>% filter(count > 50) %>% print(n=100)
ramen %>% group_by(country) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n(), se = sd/sqrt(count)) %>% arrange(mean_star) %>% filter(count > 50) %>% print(n=100)
ramen %>% group_by(country) %>% filter(stars == min(stars)) %>% arrange(stars)
ramen %>% group_by(country) %>% filter(stars == min(stars)) %>% arrange(stars) %>% print(n=100)
ramen %>% group_by(country) %>% filter(stars == min(stars)) %>% arrange(stars, country) %>% print(n=100)
ramen %>% count(style)
ramen %>% count(style) %>% arrange(n)
ramen
ramen %>% count(variety)
ramen %>% count(variety) %>% arrange(desc(n))
ramen %>% count(variety) %>% count(n)
ramen_long <- ramen %>%
mutate(variety = str_split(variety, " ")) %>%
unnest(variety)
ramen_long
ramen_long %>% count(variety) %>% arrange(desc(n))
ramen_long %>% count(variety) %>% arrange(desc(n)) %>% print(n=30)
ramen
ramen %>% group_by(bran) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n(), se = sd/sqrt(count)) %>% arrange(desc(count)) %>% print(n=100)
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n(), se = sd/sqrt(count)) %>% arrange(desc(count)) %>% print(n=100)
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), min(stars, na.rm = TRUE), max(stars, na.rm=TRUE),count = n()) %>% arrange(desc(count)) %>% print(n=100)
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), min = min(stars, na.rm = TRUE), max = max(stars, na.rm=TRUE),count = n()) %>% arrange(desc(count)) %>% print(n=100)
ramen %>% ggplot(x = brand, y = stars) + geom_boxplot()
ramen %>% ggplot(aes(x = brand, y = stars)) + geom_boxplot()
ramen %>% group_by(brand) %>% filter(n() > 30)
ramen %>% group_by(brand) %>% filter(n() > 30) %>% ggplot(aes(x = brand, y = stars)) + geom_boxplot()
ramen %>% group_by(brand) %>% filter(n() > 30) %>% ggplot(aes(x = brand, y = stars)) + geom_boxplot() + coord_flip()
ramen %>% group_by(brand) %>% filter(n() > 30) %>% mutate(m = mean(stars), r = rank(m)) %>% ggplot(aes(x = brand, y = stars, groups = r)) + geom_boxplot() + coord_flip()
ramen %>% group_by(brand) %>% filter(n() > 30) %>% mutate(m = mean(stars), r = rank(m)) %>% ggplot(aes(x = brand, y = stars, group = r)) + geom_boxplot() + coord_flip()
ramen %>% group_by(brand) %>% filter(n() > 30) %>% ggplot(aes(x = brand, y = stars, group = r)) + geom_boxplot() + coord_flip()
ramen %>% group_by(brand) %>% filter(n() > 30) %>% ggplot(aes(x = brand, y = stars)) + geom_boxplot() + coord_flip()
ramen %>% group_by(country) %>% filter(n() > 50) %>% ggplot(aes(x = country, y = stars)) + geom_boxplot() + coord_flip()
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n())
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% ggplot(aes(x=count, y= mean_star)) + geom_point()
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% ggplot(aes(x=count, y= mean_star)) + geom_point(alpha=.1)
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% ggplot(aes(x=count, y= mean_star)) + geom_point(alpha=.1) + geom_smooth()
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% ggplot(aes(x=count, y= mean_star)) + geom_point(alpha=.1) + geom_smooth(method="lm")
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% filter(count < 100) %>% ggplot(aes(x=count, y= mean_star)) + geom_point(alpha=.1) + geom_smooth(method="lm")
ramen %>% group_by(brand) %>% summarize(mean_star = mean(stars, na.rm = TRUE), sd = sd(stars,na.rm=TRUE), count = n()) %>% filter(count < 25) %>% ggplot(aes(x=count, y= mean_star)) + geom_point(alpha=.1) + geom_smooth(method="lm")
ramen
ramen %>% ggplot(aes(x=id, y=stars)) + geom_smooth() + geom_point(alpha = .1)
ramen_long
savehistory()
